baseURL = "https://clementchen.co/"
locale = "en-us"
title = "Clement Chen"
theme = "not-much"

[params]
  noindex = true
  theme = "auto"
  palette = "default"
  showThemeNotice = true
  showFooterEverywhere = true
  showPostsSummary = true

copyright = "© {year} Clement Chen"

[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts/"
  weight = 3
